unique_ids:
  assets:
    standard-page.html: H7KUDMXUJ226HAIEGQTDG233JQRZDIGX
    theme.css: HZFPWQNCTLX3CUFSMIGVCDQLLU2T7WRJ
  forms:
    Form1: WSGNCR55VIECSDRCNC2XIRZ57UEHFHZE
  modules: {}
  scripts: {}
  server_modules: {}
